---
title: "Optimizing Bed Allocation in Stroke Units: A Simulation-Based Analysis"
format: html
bibliography: reference.bib
csl: academic-medicine.csl
---

### ***Abstract***:

**Introduction**:

Geographical stroke units offer effective treatment for ischemic and hemorrhagic stroke patients. Optimal care is achieved when patients are allocated to these wards. Determining the optimal number of beds required is a complex task. This study/project leverages discrete-event simulation, grounded in queueing theory, to ascertain the ideal number of beds for optimal care given patient influx. The study utilized stroke unit data including arrival rates, bed occupation times, and stroke severity probabilities to generate realistic scenarios for the simulation model. The objective of this project was to evaluate the impact of varying bed capacities on the performance of stroke care units such as bed utilization, maximum queue length, proportion of patients waiting, and average queue length.

**Method and Design**:

The simulation model considered factors such as patient arrival rates, stroke severity probabilities, and bed occupation times. Patient arrival rates were estimated to be 6 patients/day, based on an annual patient load of \~2000. The distribution of stroke severity was as follows: very mild (probability = 0.2), mild (probability = 0.2), moderate (probability = 0.35), severe (probability = 0.1), and very severe (probability = 0.15). Bed occupation times ranged from 1 day (very mild) to 3-21 days (severe). The study explored 25-50 bed scenarios and considered an increase in patient arrival to 2500 in the near future. Simulation was run for 100 replications, evaluating performance measures (e.g., average queue length, maximum queue length, and capacity utilization) with an initial 25-bed provision.

**Discussion:**

The study utilized stroke unit data, including arrival rates, bed occupation times, and stroke severity probabilities, to generate realistic scenarios for the simulation model. A simulation model showed that the initial 25-bed provision was inadequate for the annual patient load of \~2000, leading to prolonged wait times and queues. The percent of patients queuing was around \~ 33% for 25 beds, 23% for 30 beds, and 5% for 40 beds.

***Background and Motivation***

Healthcare systems are under continual pressure to provide accessible and effective health services to patients, especially to the most vulnerable of these patients, therefore, the decisions regarding adequate provision of services to the patients is vital for optimal care of patients in the hospital. Hence, hospital capacity planning has become an important issue around the world due to the growing demand for hospital care and an increasing cost of inpatient care. Key metrics such as bed capacity and associated indices such as bed occupancy and the ratio of beds to population used to determine the availability of inpatient care [@Ravaghi2020]. The number of beds in a hospital can be conceived as a capital stock, which is influenced by the performance of medical staff and equipment [@healthGlance2017] [@liu2012] . Indeed, a shortage of available beds can seriously impact on how a hospital functions. Indeed, it is the primary cause of admission and surgery cancellations, delays in emergency admissions, early patient transfers from intensive care units, delays in patient transfers between units, and early patient discharge \[[2](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR2), [4](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR4)\]. Conversely, excess bed capacity may lead to additional costs and stagnant capital. Therefore, hospital capacity planning should consider hospital bed availability alongside issues related to productivity, and clinical efficiency \[[5](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR5),[6](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR6),[7](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR7)\].

In order to come up with better policy designs for healthcare industry, researchers, policy makers and other professionals studying the healthcare systems have made use of the simulation based modeling to replicate the real life scenarios in the healthcare units and hospitals to improve the policy framework. In the context of estimating the number of beds for a stroke care unit, the simulation based modeling is has been extensively used by the researchers due to the ease with which simulation model can be developed and the many other external events can be incorporated into the model.

Decisions about hospital bed capacity are made by policymakers and managers at different levels of the health system. Here, two main points should be considered: the time horizon for the number of hospital beds (short, medium, or long term) and levels of hospital bed capacity planning (strategic, tactical and operational levels). Strategic planning of hospital capacity at the regional level is concerned with anticipating long-term regional needs, while tactical planning occurs at the hospital level. The operational level focuses on determining the optimal number of beds to allocate to each hospital unit \[[8](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR8)\]. Changing hospital bed capacities is a highly sensitive political issue, involving complex negotiations, often with little use of economic indicators to inform decision making \[[9](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR9)\].

The number of beds required to provide quality healthcare depends on a range of factors including models of care, patient need, national policies, and local circumstances. National policies focus on how to meet this demand. Local circumstances include internal hospital processes, the availability of other services, and influence demand management at the local level. Given that the interaction of these factors varies over time and within countries, the number of beds required to deliver health services also varies \[[10](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR10)\].

Hospital bed capacity cannot be determined without taking into account hospital needs, policies, existing services, staffing patterns, and other relevant aspects. Any projections regarding hospital services and future inpatient care should also be alert to wider health system changes (e.g. demographic trends, the substitution of day care for inpatient care, and changes in average length of stay) \[[11](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR11)\]. This is because in many healthcare systems there is concerted effort to shift towards more ambulatory forms of care \[[12](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR12), [13](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR13)\]. New technologies make it possible for more complex interventions to be undertaken in ambulatory or outpatient settings. Therefore, estimating the required number of hospital beds is a challenging task as many complex factors need to be taken into account, some of which are difficult to model and predict in advance. This creates the need for sophisticated modelling and sensitivity analyses to better estimate the numbers of hospital beds required to meet changing patient needs \[[14](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR14)\]. Because of these changes and complexities, we need modular architecture and to be flexible in the design of hospitals. Therefore, heavily top-down approaches are inappropriate and it is important to allow some level of local adaptation in the designing of hospitals. Most studies focus on the optimal allocation of hospital beds and use tools such as simulation methods for this purpose. The results of these studies show that this model can be a helpful tool for hospital managers in the planning and management of hospital beds \[[14](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR14),[15](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR15),[16](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-020-5023-z#ref-CR16)\].

Against this background, the purpose of this article is to review critically the various models and methods that have been developed and deployed for determining the required number of hospital beds at hospital and regional levels, as part of strategic and tactical planning. In this review, identified models and methods will be described and compared based on their key affecting factors, their advantages, and their challenges. This review follows the methodology of a scoping review, as the aim of the present research is to provide an overview of models and methods, rather than to answer specific questions.
